name: Ping Koyeb App

on:
  schedule:
    - cron: '0 3 * * *'  # 매일 한국시간 오후 12시 (UTC 03:00)
  workflow_dispatch:     # 수동 실행도 가능

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Curl to keep Koyeb app alive
        run: curl -s --max-time 10 https://empirical-canidae-sechanglee-afaaa098.koyeb.app > /dev/null